// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nibo.Data.Context;

namespace Nibo.Data.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20200614223444_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Nibo.Business.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DTPOSTED")
                        .HasColumnName("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<string>("MEMO")
                        .IsRequired()
                        .HasColumnName("Memo")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(90);

                    b.Property<string>("TRNAMT")
                        .IsRequired()
                        .HasColumnName("Amount")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(90);

                    b.Property<int>("TRNTYPE")
                        .HasColumnName("Type")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("ACCTID");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
